### ISSUE TITLE
I know this isn't technically an issue but,

### ISSUE THREAD

**Issue by eboatwright** [gonutz/prototype#19]
It is an issue that this is so underrated! I've been trying everything everywhere from Vulkan-go to glfw-go and NOTHING worked cross platform! Thank you guys, and I'll probably contribute to this in the future! :smile:

**Comment by gonutz** [comment]
Thank you very much, I (not we, actually, just me here) really appreciate the compliment. I am actually working on a tutorial video and article to promote this library. Great to hear that it works well for you, what operating systems have you tried it on?

**Comment by eboatwright** [comment]
I did darwin amd64, and windows amd64 :smile:

**Comment by gonutz** [comment]
Oh cool, nice, I actually only ever tried it on Windows and Linux, since I do not own a Mac. The Mac support has been tested once by someone building a Ludum Dare game of mine, who reported that it worked. Good to hear you confirm that :-)

**Comment by eboatwright** [comment]
:smile:
