### ISSUE TITLE
Is more than one Window possible

### ISSUE THREAD

**Issue by kiba1210** [gonutz/prototype#6]
Is it possible to have more than one window?
It would be cool.
BTW, I like your package, it is simple and enough for what I need.

**Comment by gonutz** [comment]
You can have multiple windows one after the other :-)

What is your use case? Do you mean multiple windows at the same time, like GIMP? Since the `RunWindow` function blocks, this would only be possible using go routines but the whole idea is not supported and will not work.

Thanks for the compliment, actually the idea is to keep the API minimal and since I think multiple windows is only in 0% (rounded to the nearest integer) of cases what you want, I do not intend to support it. But if you have a legit reason for it, I might be up for it. But it has to be a very good reason :-)

**Comment by kiba1210** [comment]
Thanks for the reply :-),
as I don't really need fancy graphics or a fancy GUI, I have been thinking that during the run of application, it would be nice to have one window that is drawing, and another to enter some changes of parameters and also, as outputs from the run in real time (I have lots of information jumping out during the execution and I wouldn't like to pollute my drawing window). Because basically, I could use it as a GUI too.
But, anyway, it is a really cute, little package and it is really what I needed.
Thanks a lot for developing it.

**Comment by gonutz** [comment]
As for using this as a GUI tool, I actually have done this a couple of times in the past. The API lends itself well for use as an immediate mode GUI. Below is a preview of the code that I want to include as a sample soon. I define some GUI helper functions at the top of the Window callback and then I use these throughout the rest of the program.

```
package main

import (
	"fmt"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/gonutz/prototype/draw"
)

func main() {
	frame := 0

	type editState struct {
		text   string
		active bool
	}

	left := editState{text: "123.5"}
	op := editState{text: "+"}
	right := editState{text: "111"}

	draw.RunWindow("GUI", 500, 250, func(window draw.Window) {
		// Define some immediate mode GUI functions.
		frame++
		mouseX, mouseY := window.MousePosition()
		button := func(text string, x, y, w, h int) bool {
			color := draw.White
			if x <= mouseX && mouseX < x+w &&
				y <= mouseY && mouseY < y+h {
				color = draw.LightRed
			}
			window.FillRect(x, y, w, h, color)
			window.DrawRect(x, y, w, h, draw.Black)
			textWidth, textHeight := window.GetTextSize(text)
			window.DrawText(text, x+(w-textWidth)/2, y+(h-textHeight)/2, draw.Black)
			for _, c := range window.Clicks() {
				if c.Button == draw.LeftButton &&
					x <= c.X && c.X < x+w &&
					y <= c.Y && c.Y < y+h {
					return true
				}
			}
			return false
		}

		textEdit := func(text string, active bool, x, y, w, h int) (string, bool) {
			color := draw.White
			if active {
				color = draw.LightRed
			}
			window.FillRect(x, y, w, h, color)
			window.DrawRect(x, y, w, h, draw.Black)
			displayText := text
			if active && (frame/25)%2 == 0 {
				displayText += "|" // Text cursor at the end.
			}
			_, textHeight := window.GetTextSize(displayText)
			window.DrawText(displayText, x+5, y+(h-textHeight)/2, draw.Black)

			if active {
				// Handle keyboard input if we are the active text edit.
				if window.WasKeyPressed(draw.KeyBackspace) {
					_, size := utf8.DecodeLastRuneInString(text)
					text = text[:len(text)-size]
				}
				for _, r := range window.Characters() {
					if unicode.IsGraphic(r) {
						text += string(r)
					}
				}
			}

			for _, c := range window.Clicks() {
				if c.Button == draw.LeftButton {
					if x <= c.X && c.X < x+w &&
						y <= c.Y && c.Y < y+h {
						active = true
					} else {
						active = false
					}
				}
			}

			return text, active
		}

		label := func(text string, x, y int, color draw.Color) {
			text = " " + text + " " // Add some margin left and right.
			textWidth, textHeight := window.GetTextSize(text)
			window.FillRect(x, y, textWidth, textHeight, draw.White)
			window.DrawText(text, x, y, color)
		}

		// Draw the GUI.
		window.FillRect(0, 0, 9999, 9999, draw.DarkGreen)
		if button("Close", 10, 30, 80, 30) {
			window.Close()
		}
		if button("Fullscreen", 10, 70, 100, 30) {
			window.SetFullscreen(true)
		}
		if button("Windowed", 120, 70, 100, 30) {
			window.SetFullscreen(false)
		}
		left.text, left.active = textEdit(left.text, left.active, 10, 120, 100, 30)
		op.text, op.active = textEdit(op.text, op.active, 120, 120, 50, 30)
		right.text, right.active = textEdit(right.text, right.active, 190, 120, 100, 30)
		if button("Clear", 320, 120, 80, 30) {
			left.text = ""
			op.text = ""
			right.text = ""
			left.active = true
		}

		// Use our GUI state to do the calculation.
		a, aErr := strconv.ParseFloat(left.text, 64)
		b, bErr := strconv.ParseFloat(right.text, 64)
		isKnownOp := op.text != "" && strings.Contains("+-*/", op.text)
		if aErr == nil && bErr == nil && isKnownOp {
			var result float64
			switch op.text {
			case "+":
				result = a + b
			case "-":
				result = a - b
			case "*":
				result = a * b
			case "/":
				result = a / b
			}
			label("= "+fmt.Sprint(result), 10, 180, draw.Black)
			_ = a + b
		} else {
			label("Invalid computation", 10, 180, draw.Red)
		}
	})
}
```

**Comment by kiba1210** [comment]
Cool !!!
I will try it 👍 
When I was talking about multi windows, it's because (in my case) I could channel my different outputs to different windows, having them on multiple screens. In my case, it would allow me to have a full control station on my desk. Moreover, it could allow different people to be feed only with information "for their eyes only" :-)
Anyway, I thank you a lot for discussing with me and providing me some incites on your packages'  GUI abilities.
Thank You very much

**Comment by gonutz** [comment]
I want to thank you for your input! Happy to talk to you again if you have any other use cases for the library.

It sounds like what you do is out of the scope of this lib and stands in contrast to the requirement of having a small API. Of course you could actually create one very large window, create implementations of `draw.Window` that only draw to sub-regions of the main `draw.Window` and pass each of your sub-systems one of these bounded `draw.Window`s. I like thinking about these things and how I would go about a use case like it without changing the API. It is almost always possible to move the complexity of the problem into either layer, the underlying API or the main program itself.

Anyway, I will close this issue then, but feel free to keep the discussion open. It is just that I will not, for now, be implementing mutliple window support.

**Comment by kiba1210** [comment]
Cool,
Thank You again, it was a pleasure 💯
